services:
  server:
      build: ./backend/
      container_name: serverContainer
      ports:
        - "${SERVER_PORT}:${SERVER_PORT}"
        - "51212:51212"
      env_file:
        - ./backend/.env     # SERVER-specific environment
      volumes:
        - ./backend:/app
        - /app/node_modules
      depends_on:
        - db

  db:
    image: postgres:16-alpine
    container_name: dbContainer
    restart: always
    env_file:
      - ./.env 
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PSWD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes: 
      - smarthomedb-data:/var/lib/postgresql/data

  react:
      build: ./frontend/
      container_name: frontendContainer
      ports:
        - "${REACT_PORT}:${REACT_PORT}"
      env_file:
        - ./.env     # SERVER-specific environment
      volumes:
        - ./frontend:/app
        - /app/node_modules
      environment:
        - CHOKIDAR_USEPOLLING=true
        - WATCHPACK_POLLING=true
      depends_on:
        - server

volumes:
  smarthomedb-data: